INSERT INTO `_system_module` ( `ID__system_menu_item_sm_menu`, `sm_name`, `sm_order`, `sm_java_class`, `sm_alternative_text`, `sm_description`, `sm_show`, `sm_position`, `sm_default_parameters`, `sm_default_call`, `sm_auto_load`, `ID__system_meta_environment_sme_modules`, `creation_date`, `creation_user`, `last_modification_date`, `last_modification_user`, `deletion_date`, `deletion_user`, `deletion_flag`, `activation_flag`) VALUES
( 0, 'export', 1, 'eu.anastasis.serena.application.modules.report.ReportModule', '', 'Modulo Esportazione', '', 5, '', '', NULL, 1, '2010-03-09', 'admin', NULL, NULL, NULL, '0', 0, 1);

INSERT INTO _system_instance_auth ( ID, ID__system_group_sia_group, sia_permissions, activation_flag, deletion_flag, creation_user, creation_date, last_modification_user, last_modification_date, sia_instance, sia_class ) VALUES( 79, "5", "111", "1", "0", "admin", "2012-05-04", "admin", "2012-05-04", "41", "_system_module" );
INSERT INTO _system_instance_auth ( ID, ID__system_group_sia_group, sia_permissions, activation_flag, deletion_flag, creation_user, creation_date, last_modification_user, last_modification_date, sia_instance, sia_class ) VALUES( 80, "1", "111", "1", "0", "admin", "2012-05-04", "admin", "2012-05-04", "41", "_system_module" );
INSERT INTO _system_instance_auth ( ID, ID__system_group_sia_group, sia_permissions, activation_flag, deletion_flag, creation_user, creation_date, last_modification_user, last_modification_date, sia_instance, sia_class ) VALUES( 81, "2", "111", "1", "0", "admin", "2012-05-04", "admin", "2012-05-04", "41", "_system_module" );

UPDATE _system_menu_item SET smi_locale = "it" , ID__system_menu_item_smi_children = "45" , activation_flag = "1" , smi_alternative_text = "Fatture" , smi_title = "Fatture" , smi_href = "?q=object/filter&p=Fattura_Totali" , smi_association = NULL , smi_order = "9" , last_modification_user = "admin" , last_modification_date = "2012-05-04"  WHERE ID = 53;


update `Cliente` c set `codice_cliente` = concat(`codice_cliente`,',',(select cod3 from _imp_codici_clienti i where c.codice_cliente = i.cod6)) where exists (select 1 from _imp_codici_clienti i2 where c.codice_cliente = i2.cod6);
INSERT INTO _system_menu_item ( ID, smi_href, smi_order, ID__system_menu_item_smi_children, smi_locale, smi_title, activation_flag, smi_alternative_text, deletion_flag, creation_user, creation_date, last_modification_user, last_modification_date ) VALUES( 82, "?q=object/filter&p=DatiContabili", "3", "12", "it", "Ricerca ed esportazione per dati contabili", "1", "Ricerca ed esportazione clienti per dati contabili", "0", "admin", "2012-05-07", "admin", "2012-05-07" );
INSERT INTO _system_menu_item ( ID, smi_href, smi_order, ID__system_menu_item_smi_children, smi_locale, smi_title, activation_flag, smi_alternative_text, deletion_flag, creation_user, creation_date, last_modification_user, last_modification_date ) VALUES( 83, "?q=object/filter&p=DatiCRM", "5", "12", "it", "Ricerca ed esportazione per dati CRM", "1", "Ricerca ed esportazione clienti per dati CRM", "0", "admin", "2012-05-07", "admin", "2012-05-07" );
